import { doc, getDoc, Timestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { couponAvailability, couponDiscount, normalizeCoupon, type StoreCoupon } from "@/lib/coupons";
export type PublicPromotion = StoreCoupon;
export type PromotionOpportunity = { kind:"available"; coupon:PublicPromotion; discount:number } | { kind:"near"; coupon:PublicPromotion; missing:number };
const KEY="dfl-public-promotions-v1", TTL=10*60*1000;
let memory:{expiresAt:number;items:PublicPromotion[]}|null=null;
function hydrate(values:unknown[]):PublicPromotion[]{return values.map((value)=>{const raw=value&&typeof value==="object"?value as Record<string,unknown>:{};return normalizeCoupon(String(raw.code??""),{ativo:raw.active===true,tipo:raw.type,valor:raw.value,minOrder:raw.minOrder,description:raw.description,startsAt:typeof raw.startsAt==="number"?Timestamp.fromMillis(raw.startsAt):raw.startsAt,expiresAt:typeof raw.expiresAt==="number"?Timestamp.fromMillis(raw.expiresAt):raw.expiresAt});}).filter((c)=>Boolean(c.code));}
function serialize(items:PublicPromotion[]){return items.map((c)=>({code:c.code,active:c.active,type:c.type,value:c.value,minOrder:c.minOrder,description:c.description,startsAt:c.startsAt?.toMillis()??null,expiresAt:c.expiresAt?.toMillis()??null}));}
export async function getPublicPromotions():Promise<PublicPromotion[]>{const now=Date.now();if(memory&&memory.expiresAt>now)return memory.items;if(typeof window!=="undefined"){try{const raw=sessionStorage.getItem(KEY);const cached=raw?JSON.parse(raw) as {expiresAt?:number;items?:unknown[]}:null;if(cached?.expiresAt&&cached.expiresAt>now&&Array.isArray(cached.items)){const items=hydrate(cached.items);memory={expiresAt:cached.expiresAt,items};return items;}}catch{}}const snap=await getDoc(doc(db,"settings","publicPromotions"));const items=snap.exists()&&Array.isArray(snap.data()?.items)?hydrate(snap.data().items as unknown[]):[];const expiresAt=now+TTL;memory={expiresAt,items};if(typeof window!=="undefined"){try{sessionStorage.setItem(KEY,JSON.stringify({expiresAt,items:serialize(items)}));}catch{}}return items;}
export function selectPromotionOpportunity(promotions:PublicPromotion[],subtotal:number,now=Date.now()):PromotionOpportunity|null{if(subtotal<=0)return null;const current=promotions.filter((c)=>c.active&&c.value>0&&(!c.startsAt||c.startsAt.toMillis()<=now)&&(!c.expiresAt||c.expiresAt.toMillis()>=now));const available=current.filter((c)=>couponAvailability(c,subtotal,now).ok).map((coupon)=>({coupon,discount:couponDiscount(coupon,subtotal)})).filter((x)=>x.discount>0).sort((a,b)=>b.discount-a.discount)[0];if(available)return{kind:"available",...available};const near=current.filter((c)=>c.minOrder>subtotal).map((coupon)=>({coupon,missing:coupon.minOrder-subtotal})).sort((a,b)=>a.missing-b.missing)[0];return near?{kind:"near",...near}:null;}
