"use client";
import { useMemo,useState } from "react";
import { Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { useAnalyticsReportsV2,type AnalyticsDayV2 } from "@/hooks/useAnalyticsReportsV2";
import styles from "./RelatoriosAdmin.module.css";
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),compact=(v:number)=>new Intl.NumberFormat("pt-BR",{notation:"compact",maximumFractionDigits:1}).format(v);
const label=(k:string)=>({pix:"PIX",dinheiro:"Dinheiro",site:"Site próprio",loja:"Loja / manual",manual:"Loja / manual",ifood:"iFood",nao_informado:"Não informado",pickup:"Retirada"}[k]||k.replaceAll("_"," "));
const dk=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d),shift=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n);return dk(d)};
function merge(days:AnalyticsDayV2[]){const o={sales:0,revenue:0,subtotal:0,deliveryFees:0,discounts:0,delivery:0,pickup:0,scheduled:0,immediate:0,logisticsCompleted:0,payments:{} as Record<string,number>,products:{} as Record<string,number>,origins:{} as Record<string,number>};for(const d of days){for(const k of ["sales","revenue","subtotal","deliveryFees","discounts","delivery","pickup","scheduled","immediate","logisticsCompleted"] as const)o[k]+=Number(d[k]||0);for(const[k,v]of Object.entries(d.payments||{}))o.payments[k]=(o.payments[k]||0)+Number(v);for(const[k,v]of Object.entries(d.products||{}))o.products[k]=(o.products[k]||0)+Number(v);for(const[k,v]of Object.entries(d.origins||{}))o.origins[k]=(o.origins[k]||0)+Number(v)}return o}
const Tip=({active,payload,label:day}:any)=>active&&payload?.length?<div className={styles.tip}><b>{day}</b>{payload.map((x:any)=><span key={x.dataKey}>{x.name}: {x.dataKey==="revenue"?money(Number(x.value)):x.value}</span>)}</div>:null;
export function RelatoriosAdmin({pedidos}:{pedidos:any[]}){const[period,setPeriod]=useState<"today"|"yesterday"|"7d"|"30d"|"all">("7d");const{days,loading,error,reload,source,persistentError}=useAnalyticsReportsV2(pedidos);const selected=useMemo(()=>{const today=dk(new Date());if(period==="today")return days.filter(d=>d.dateKey===today);if(period==="yesterday")return days.filter(d=>d.dateKey===shift(1));if(period==="7d")return days.filter(d=>d.dateKey>=shift(6)&&d.dateKey<=today);if(period==="30d")return days.filter(d=>d.dateKey>=shift(29)&&d.dateKey<=today);return days},[days,period]);const m=useMemo(()=>merge(selected),[selected]),ticket=m.sales?m.revenue/m.sales:0;const timeline=[...selected].sort((a,b)=>a.dateKey.localeCompare(b.dateKey)).map(d=>({date:d.dateKey.slice(5).split("-").reverse().join("/"),revenue:d.revenue,sales:d.sales}));const origins=Object.entries(m.origins).map(([name,value])=>({name:label(name),value})).sort((a,b)=>b.value-a.value),payments=Object.entries(m.payments).map(([name,value])=>({name:label(name),value})).sort((a,b)=>b.value-a.value),products=Object.entries(m.products).sort((a,b)=>b[1]-a[1]).slice(0,10);
return <div className={styles.root}><div className={styles.filters}>{[["Hoje","today"],["Ontem","yesterday"],["7 dias","7d"],["30 dias","30d"],["Tudo","all"]].map(([l,v])=><button key={v} data-active={period===v} onClick={()=>setPeriod(v as typeof period)}>{l}</button>)}</div>{loading?<section className={styles.panel}><div className={styles.noData}>Carregando inteligência…</div></section>:error?<section className={styles.panel}><div className={styles.noData}>Relatórios indisponíveis. <button onClick={reload}>Tentar novamente</button></div></section>:<>{source==="live-fallback"&&<section className={styles.notice}>Visão temporária apenas dos pedidos do Site{persistentError?" · projeção persistente indisponível":""}.</section>}<div className={styles.kpis}><article><span>Faturamento</span><strong>{money(m.revenue)}</strong><small>vendas finalizadas</small></article><article><span>Pedidos</span><strong>{m.sales}</strong><small>{m.delivery} entregas · {m.pickup} retiradas</small></article><article><span>Ticket médio</span><strong>{money(ticket)}</strong><small>por pedido</small></article><article><span>Logística</span><strong>{m.logisticsCompleted}</strong><small>conclusões registradas</small></article></div>
<section className={styles.panel}><header><div><span>DESEMPENHO</span><h3>Faturamento no período</h3></div><small>{m.sales} pedidos</small></header><div className={styles.bigChart}>{timeline.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline} margin={{top:8,right:4,left:-20,bottom:0}}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity={.28}/><stop offset="100%" stopColor="currentColor" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)"/><XAxis dataKey="date" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip content={<Tip/>}/><Area type="monotone" dataKey="revenue" name="Faturamento" stroke="currentColor" fill="url(#rev)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer>:<div className={styles.noData}>Sem vendas no período.</div>}</div></section>
<div className={styles.split}><section className={styles.panel}><header><div><span>ORIGEM</span><h3>De onde vêm os pedidos</h3></div></header>{origins.length?<><div className={styles.donut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={origins} dataKey="value" nameKey="name" innerRadius="62%" outerRadius="88%" paddingAngle={3}>{origins.map((_,i)=><Cell key={i} className={styles["slice"+(i%4)]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div><b>{m.sales}</b><span>pedidos</span></div></div><div className={styles.legend}>{origins.map((x,i)=><div key={x.name}><i className={styles["dot"+(i%4)]}/><span>{x.name}</span><b>{x.value} · {m.sales?Math.round(x.value/m.sales*100):0}%</b></div>)}</div></>:<div className={styles.noData}>Origem ainda não materializada.</div>}</section>
<section className={styles.panel}><header><div><span>PAGAMENTOS</span><h3>Faturamento por forma</h3></div></header><div className={styles.barChart}>{payments.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={payments} layout="vertical" margin={{left:0,right:12}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={88} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="value" name="Faturamento" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer>:<div className={styles.noData}>Sem pagamentos no período.</div>}</div></section></div>
<section className={styles.panel}><header><div><span>OPERAÇÃO</span><h3>Composição das vendas</h3></div></header><div className={styles.stats}><div><span>Subtotal</span><b>{money(m.subtotal)}</b></div><div><span>Taxas</span><b>{money(m.deliveryFees)}</b></div><div><span>Descontos</span><b>{money(m.discounts)}</b></div><div><span>Agendados</span><b>{m.scheduled}</b></div><div><span>Imediatos</span><b>{m.immediate}</b></div><div><span>Retiradas</span><b>{m.pickup}</b></div></div></section>
<section className={styles.panel}><header><div><span>PRODUTOS</span><h3>Mais vendidos</h3></div><small>Pedidos manuais sem itens não entram neste ranking</small></header><div className={styles.ranking}>{products.length?products.map(([n,q],i)=><div key={n}><em>{String(i+1).padStart(2,"0")}</em><span>{n}</span><b>{q} un.</b></div>):<div className={styles.noData}>Sem produtos no período.</div>}</div></section></>}</div>}
